var tune_data = {
    "tune_text":"img/toteron.png",
    "tune_ogg":"snd/tote_eron.ogg",
    "tune_mp3":"snd/tote_eron.mp3",
    "places":[
        {
            "left":"10",
            "top":"60",
            "duration":"2000",
            "mode":"0",
            "time":"0"
        },
        {
            "left":"100",
            "top":"60",
            "duration":"2000",
            "mode":"0",
            "time":"2"
        },
        {
            "left":"200",
            "top":"60",
            "duration":"2000",
            "mode":"0",
            "time":"4"
        },
        {
            "left":"300",
            "top":"60",
            "duration":"2000",
            "mode":"0",
            "time":"6"
        },
        {
            "left":"400",
            "top":"60",
            "duration":"2000",
            "mode":"1",
            "time":"8"
        },
        {
            "left":"10",
            "top":"90",
            "duration":"2000",
            "mode":"0",
            "time":"10"
        },
        {
            "left":"100",
            "top":"90",
            "duration":"2000",
            "mode":"0",
            "time":"12"
        },
        {
            "left":"200",
            "top":"90",
            "duration":"2000",
            "mode":"0",
            "time":"14"
        },
        {
            "left":"300",
            "top":"90",
            "duration":"2000",
            "mode":"0",
            "time":"14"
        },
        {
            "left":"400",
            "top":"90",
            "duration":"2000",
            "mode":"0",
            "time":"14"
        }
        
    ]
};